### ISSUE TITLE
DEB build

### ISSUE THREAD

**Issue by m1guelpf** [getstation/desktop-app-releases#1] opened 2017-10-04 10:45 UTC
How about a .deb build?

**Comment by magne4000** [comment] 2017-11-02 18:36
Linux builds are on their way. We'll start with a `snap` package.

**Comment by m1guelpf** [comment] 2017-11-02 18:38
@magne4000 Thank you! Do you have an estimated timeline on when will it be ready?

**Comment by magne4000** [comment] 2017-11-02 18:42
We already have a linux build ready, but it's currently in private beta to see that everything works as intended.
We also need to ensure that all snap related workflow (regarding auto updates) is working correctly. This is the point on which we do not have time to work on right now, but we hope having time to close this point before the end of the year 😉

**Comment by fgroch** [comment] 2017-12-20 10:11
@magne4000  I'm looking forward for linux version  ...

**Comment by davidecavestro** [comment] 2018-04-06 15:16
Any news? I'd be more than happy to contribute

**Comment by matheuslemke** [comment] 2018-07-20 11:36
@magne4000 Waiting for snap build. I'm able to help too :smiley:

**Comment by MathieuDebit** [comment] 2018-09-24 08:48
Hi everyone,

We now have a linux support! You can download the AppImage on https://getstation.com ✨

**Closed by MathieuDebit** 2018-09-24 08:48 UTC
